apiVersion: v1
kind: Service
metadata:
  name: model-service
spec:
  selector:
    app: model
  ports:
  - protocol: TCP
    port: 5000  # Port exposed by the service
    targetPort: 5000  # Port on which the container listens
  type: LoadBalancer  # Expose the service externally with a cloud provider's load balancer
