apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlops-app
  template:
    metadata:
      labels:
        app: mlops-app
    spec:
      containers:
      - name: mlops-container
        image: m3mlops.azurecr.io/m3model:v3
        ports:
        - containerPort: 5000
